# Generated by Django 5.0.7 on 2024-07-22 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('locations', '0001_initial'),
        ('users', '0003_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
                ('location_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_location', to='locations.location')),
                ('location_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_location', to='locations.location')),
                ('responsible_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_user', to='users.user')),
                ('responsible_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_user', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
