# Generated by Django 5.0.7 on 2024-11-25 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0002_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('release_equipment', 'Release Equipment'), ('inventory', 'Inventory'), ('moving_withour_notice', 'Moved without nothing'), ('release_cartridge', 'Release Cartridge')], default='inventory', max_length=50)),
                ('date', models.DateTimeField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
                ('location_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_location', to='locations.location')),
                ('location_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_location', to='locations.location')),
            ],
        ),
    ]
