# Generated by Django 5.0.7 on 2024-11-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("release_equipment", "Release Equipment"),
                    ("inventory", "Inventory"),
                    ("moving_withour_notice", "Moved without nothing"),
                    ("release_cartridge", "Release Cartridge"),
                ],
                default="inventory",
                max_length=50,
            ),
        ),
    ]
