# Generated by Django 5.0.7 on 2025-01-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_alter_cartridge_status'),
        ('operations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='cartridge_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartridge_old', to='equipments.cartridge'),
        ),
    ]
