# Generated by Django 5.0.7 on 2024-11-26 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_alter_cartridge_status'),
        ('operations', '0003_operation_cartridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment'),
        ),
    ]
