# Generated by Django 5.0.7 on 2024-11-26 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        ('operations', '0004_alter_operation_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='location_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_location', to='locations.location'),
        ),
    ]
