# Generated by Django 5.0.7 on 2024-12-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode",
                    models.ImageField(
                        blank=True, upload_to="barcodes/", verbose_name="Штрих код"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartridgeTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "type Картридж",
                "verbose_name_plural": "type Картриджи",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "date_last_invent",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последней инвентаризации",
                    ),
                ),
                (
                    "date_last_check",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата последней проверки"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="equipment_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_true_position",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Cartridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Цвет"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("filled", "Filled"),
                            ("new", "new"),
                            ("empty", "empty"),
                            ("defective", "defective"),
                            ("release", "release"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                (
                    "is_true_position",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "cartridge_barcode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipments.barcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картридж",
                "verbose_name_plural": "Картриджи",
            },
        ),
    ]
