# Generated by Django 5.0.7 on 2024-12-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipments", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartridge",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.location",
                verbose_name="Местонахождение",
            ),
        ),
    ]
