# Generated by Django 5.0.7 on 2024-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_equipment_location_equipment_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
    ]
