# Generated by Django 5.0.7 on 2024-11-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='status',
            field=models.CharField(choices=[('filled', 'Filled'), ('new', 'new'), ('empty', 'empty'), ('defective', 'defective'), ('release', 'release')], default='new', max_length=50),
        ),
    ]
