# Generated by Django 5.0.7 on 2024-07-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_equipment_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equ-images/'),
        ),
    ]
