# Generated by Django 5.0.7 on 2024-12-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipments.equipment",
                    ),
                ),
                (
                    "cartridge_types",
                    models.ManyToManyField(to="equipments.cartridgetypes"),
                ),
            ],
            bases=("equipments.equipment",),
        ),
    ]
