# Generated by Django 5.0.7 on 2024-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_true_position',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
