# Generated by Django 5.1.4 on 2025-01-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('broken', 'Broken'), ('new', 'new'), ('renovated', 'Renovated')], default='new', max_length=144),
        ),
    ]
