# Generated by Django 5.0.7 on 2024-10-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0004_equipment_is_true_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
    ]
