# Generated by Django 5.0.7 on 2024-11-14 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_alter_equipment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipments.equipment')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
            bases=('equipments.equipment',),
        ),
    ]
