# Generated by Django 5.0.7 on 2024-07-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_remove_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagesequipments/'),
        ),
    ]
