# Generated by Django 5.0.7 on 2024-11-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_cartridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='filled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
