# Generated by Django 5.1.4 on 2025-01-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_alter_barcode_barcode_alter_equipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='zpl_barcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcodes/', verbose_name='Штрих код'),
        ),
    ]
