# Generated by Django 5.0.7 on 2024-07-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_equipment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='image',
        ),
    ]
