# Generated by Django 5.0.7 on 2024-11-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_cartridge_filled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
        ),
        migrations.AddField(
            model_name='cartridge',
            name='cartridge_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.cartridgetypes', verbose_name='Тип катриджа'),
        ),
    ]
