# Generated by Django 5.0.7 on 2024-11-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0008_cartridgetypes_cartridge_cartridge_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartridge",
            name="status",
            field=models.CharField(
                choices=[("filled", "Filled"), ("new", "new"), ("empty", "empty")],
                default="new",
                max_length=50,
            ),
        ),
    ]
