# Generated by Django 5.0.7 on 2024-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_remove_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
