# Generated by Django 5.0.7 on 2024-11-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0009_cartridge_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartridgetypes",
            options={
                "verbose_name": "type Картридж",
                "verbose_name_plural": "type Картриджи",
            },
        ),
        migrations.AlterField(
            model_name="cartridge",
            name="status",
            field=models.CharField(
                choices=[
                    ("filled", "Filled"),
                    ("new", "new"),
                    ("empty", "empty"),
                    ("defective", "defective"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
