# Generated by Django 5.0.7 on 2024-11-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0010_alter_cartridgetypes_options_alter_cartridge_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartridge",
            name="filled",
        ),
    ]
