# Generated by Django 5.0.7 on 2024-12-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_user_type_delete_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.CharField(blank=True, choices=[('accounting', 'Accounting'), ('administration', 'Administration')], max_length=255, null=True),
        ),
    ]
