# Generated by Django 5.0.7 on 2024-12-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField()),
                ("cnt", models.IntegerField(blank=True, null=True)),
                (
                    "date_last_invent",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последней инвентаризации",
                    ),
                ),
            ],
        ),
    ]
