# Generated by Django 5.1.4 on 2025-02-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(default='self', max_length=255),
            preserve_default=False,
        ),
    ]
