# Generated by Django 5.0.7 on 2024-07-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
