# Generated by Django 5.0.7 on 2024-10-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_location_cnt"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="date_last_invent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата последней инвентаризации"
            ),
        ),
    ]
