# Generated by Django 5.0.7 on 2024-12-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
