# Generated by Django 5.0.7 on 2024-12-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category_report',
            field=models.CharField(blank=True, choices=[('inventory', 'Inventory')], max_length=255, null=True),
        ),
    ]
