# Generated by Django 5.1.4 on 2025-04-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
    ]
